# .github/workflows/main.yml

name: Node.js CI/CD Pipeline

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use Node.js version 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: docker build -t node_emilsoderqvist.com .

      # Step 5: Kill Old Docker Container
      - name: Kill Old Docker Container
        run: docker rm -f node_emilsoderqvist.com || true

      # Step 5: Kill Old Docker Image
      - name: Prune Old Docker Images
        run: docker system prune -f

      # Step 6: Run New Docker Image
      - name: Run New Docker Image
        run: docker run -d -name node_emilsoderqvist.com -p 3000:3000 node_emilsoderqvist.com
