# .github/workflows/main.yml

name: Node.js CI/CD Pipeline

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use Node.js version 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build Docker image
      - name: Build Docker Image
        run: docker build -t node_emilsoderqvist.com .

      # Step 5: Kill Old Docker image
      - name: Kill Old Docker Image
        run: docker stop node_emilsoderqvist.com && docker rm node_emilsoderqvist.com

      # Step 6: Run New Docker image
      - name: Run New Docker Image
        run: docker run -d node_emilsoderqvist.com -p 3000:3000
